language: node_js
sudo: false
node_js:
  - node
before_install:
  - chmod +x travis-renameRef.sh
  - chmod +x travis-refreshApiReferenceSearchIndex.sh  
install:  
  - npm install
before_script:
    - git config pull.rebase false
    - git remote set-branches --add origin $TRAVIS_BRANCH
    - git fetch
    # - export CHANGED_FILES=`git diff --name-only --diff-filter=AM $TRAVIS_BRANCH...HEAD`
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
         export CHANGED_FILES=`git diff --name-only $TRAVIS_COMMIT_RANGE`;
      else
        export CHANGED_FILES=`git diff --name-only $TRAVIS_COMMIT_RANGE`;
      fi
    # - if [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
    #       # This isn't a PR build.
    #       COMMIT_RANGE="$(echo $TRAVIS_COMMIT_RANGE | cut -d '.' -f 1,4 --output-delimiter '..')"
    #       CHANGED_FILES="$(git diff --name-only $COMMIT_RANGE --)"
    #   else
    #       # This is a PR build.
    #       CHANGED_FILES="$(git diff --name-only $TRAVIS_BRANCH..HEAD --)"
    #   fi
script:
  - echo $TRAVIS_PULL_REQUEST
  - echo $CHANGED_FILES
  - npm test
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./travis-refreshApiReferenceSearchIndex.sh;
    fi
  - node validator/master/postSuccessComment.js
after_failure:
  - node validator/master/postDetailsComment.js
after_script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./travis-renameRef.sh;
    fi  
env:
  global:
    - SEARCHINDEXHOST=https://api.totvs.com.br
    - secure: 5MR559eBAJ3a1dGgUjGScOkt1pISp38X7EmYJlhvSahuFVL5eTxZDTzHveZvt4wFhXw0KL9pbsFb0eDQS+Gvkw5R61p63ap0OoYmpi2XfuHb3i9MYa2AtIwaW3Sz6BQVEvdAhrHGGx70mA9sxxid0+kk3nD8seY/rtastZ1vaiVwNCPpfKjwcipYpnbQbpH/2L3e3d57BGNcuM8wqqyYFtu8Sx9xO/MZTeGj7aTQroF4WlFMNhuNo2Btb2xdRpX4yaesXr1AHLozrVtiKyRDhk0huGfd9IiNyi8sgLrIBhoTVpGlpbfKgELl84ex9zdAme7uakd3RG5nMPJ7obEVx+MIWd5tU5etqw3kZa3y2AJkGZN+kHeu3PFjwq9bA4QNduUfsNaxacPnPAnz7S+bp9/JMN+kagKJbE7TRsgP1JpFDQiVv/CIjX1Caom5MNTRICzb0tvtm9/F/tdzX9qPsaLfIzfiyfMWeBJKEoK1dD3doNfVDRddlU2FYkPwq5eLS/oBXsxmVOREdvoJdGqwg2f82HOo27J/Lh1HMSzl/5LNU+LgxtaojeutgtelWTtMqvX+6poH3MeNozDQYzkdPkjdCUUdqNt/uMdDawMZMU2j2kMPrv1pfGO1Qm3D0pZELPv+efQiq95svUFM5KoW9G4HDfS/dLJ9OoH/tzxxE2M=
    - TRAVIS_JOB_ID=$TRAVIS_JOB_ID
    - TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
    - TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID
    - TRAVIS_BUILD_WEB_URL=$TRAVIS_BUILD_WEB_URL
    - CHANGED_FILES=""
    - COMMIT_RANGE=""