language: node_js
sudo: false
node_js:
- node
before_install:
- chmod +x travis-renameRef.sh
install:
- npm install
script:
- echo "Bump version and flyway migrate db"
- if [ "$TRAVIS_BRANCH" == "testChangesTravis" ]; then ./travis-renameRef.sh; fi
env:
  global:
    secure: ef2A3YjFXrZM5n+ZPR+LaKjXWcXOQuwFaHUmtoauKfpe4f2XQ1Ik+OXneTwSaa6md5Gz1ySe3R6qtIeOBCx52CP9OMsnVt6XV5pbL2YZNUqRWcbbljH46RHhoujJVjKyogo8csvUk3nEyUvFKDRgmpxjJ3yIw8D99X5W6kpskywBNkAMDUUDoJ79d1llr2Aw0bHh1UtxbHCrlu/rJgF36F4AXKWAdduMryrQ08M3VR6KUqX7lfpSg1yypytdYhXd0L6RbBShLYM2CSKH4qJZZQBs5RDY07Ea/7HlFDexVhYm24lRBV5vBFBIcFDefN9nz9/DyrYjEAUpYvneXw1sWeElXlN6W1jseuGERNDS0aDXuy7F44kZdn062ARebSEuMDdeDFPZeRI1SNrqoNBkq3R8/9kxJ30W/O7bkr8/yJk6hXSjzPKyYqi+AqNXej55m1dIh88ID5scG8NXJOqkb+Eqd/7/uOwrULu4UuAkcUbIkwBPindXfn69csLhKvpq7iMzSVhu9ESr9pot0OevmwxAMZ4pooaeuhTRi9IoRw/Yk1xbUl0CrNXOVkHA9OzIUkabPkfm4Q/Nnf0puZp9ErvLlMqBciefyCIVwWJgBj5LV2KAg2TEqxDfyaqt1Fd4wgTZ+sbGTkFgjifXtuA8BVOnQtTVipH7MFotkKjUDf4=
